package e_exception.c_throw_throws;

class Test {
    public static void main(String[] args) throws Exception {
        //throw-throws 基本语法
        //1.throws
        //void f() throws Exception（或其子类）1, Exception2, ... {
        //  //出现问题，则将问题抛到调用它的地方
        //  //如果不指定使用 try-catch-finally 处理异常，则默认使用 throws 处理异常
        //  //一般要显式地 throws 异常
        //  //可以抛出多种异常，异常之间以逗号分隔
        //  //当出现异常时检查是否位于异常列表中，如果存在就抛出异常，否则报错后退出
        //}
        //2.throw
        //throw 一个具体的异常对象
    }
}
